export const RECEIVE_TOPICS = 'RECEIVE_TOPICS'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

// cart
export const BUY_BOOK = 'BUY_BOOK'
export const DELETE_BOOK_FROM_CART = 'DELETE_BOOK_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const SWITCH_BOOK_CHECK_STATE = 'SWITCH_BOOK_CHECK_STATE'
export const SWITCH_ALL_BOOKS_CHECK_STATE = 'SWITCH_ALL_BOOKS_CHECK_STATE'